CREATE TABLE `USERS` (
  `ID`            INT         NOT NULL AUTO_INCREMENT,
  `NAME`          VARCHAR(45) NOT NULL,
  `LAST_NAME`     VARCHAR(45) NOT NULL,
  `LOGIN`         VARCHAR(45) NOT NULL,UNIQUE(LOGIN),
  `PASSWORD`      VARCHAR(45) NOT NULL,
  `EMAIL`         VARCHAR(45) NOT NULL,UNIQUE(EMAIL),
  `USER_ROLE_ID`  INT NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `USER_ROLES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ROLE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ROLE_UNIQUE` (`ROLE` ASC));

ALTER TABLE `USERS` ADD FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ROLES (ID ASC);

ALTER TABLE `USERS`
ADD CONSTRAINT `FK_USER_ROLE`
FOREIGN KEY (`USER_ROLE_ID`)
REFERENCES `USER_ROLES` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
