package com.source.it.payment.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-06-24T15:04:13.893+03:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://stub.payment.it.source.com/", name = "PaymentStub")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymentStub {

    @WebMethod
    @RequestWrapper(localName = "processPaymentBean", targetNamespace = "http://stub.payment.it.source.com/", className = "com.source.it.payment.stub.ProcessPaymentBean")
    @ResponseWrapper(localName = "processPaymentBeanResponse", targetNamespace = "http://stub.payment.it.source.com/", className = "com.source.it.payment.stub.ProcessPaymentBeanResponse")
    @WebResult(name = "response", targetNamespace = "")
    public com.source.it.payment.stub.PaymentBean processPaymentBean(
        @WebParam(name = "paymentBean", targetNamespace = "")
        com.source.it.payment.stub.PaymentBean paymentBean
    ) throws PaymentFault_Exception;
}
