
package com.source.it.payment.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-06-28T20:31:13.440+03:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "PaymentFault", targetNamespace = "http://stub.payment.it.source.com/")
public class PaymentFault_Exception extends Exception {
    
    private com.source.it.payment.stub.PaymentFault paymentFault;

    public PaymentFault_Exception() {
        super();
    }
    
    public PaymentFault_Exception(String message) {
        super(message);
    }
    
    public PaymentFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PaymentFault_Exception(String message, com.source.it.payment.stub.PaymentFault paymentFault) {
        super(message);
        this.paymentFault = paymentFault;
    }

    public PaymentFault_Exception(String message, com.source.it.payment.stub.PaymentFault paymentFault, Throwable cause) {
        super(message, cause);
        this.paymentFault = paymentFault;
    }

    public com.source.it.payment.stub.PaymentFault getFaultInfo() {
        return this.paymentFault;
    }
}
